mkdir -p src/orioncore/drivers_raw
mkdir -p src/kernel/scheculer
mkdir -p src/kernel/syscall
mkdir -p src/kernel/vfs
mkdir -p src/kernel/mm
mkdir -p src/kernel/sync
mkdir -p src/kernel/drivers
mkdir -p src/kernel/elf
mkdir -p src/libs/libc
mkdir -p src/libs/libio
mkdir -p src/libs/libm
mkdir -p src/libs/libvideo
mkdir -p src/libs/librtc
mkdir -p src/libs/klib
mkdir -p src/shell
mkdir -p src/apps
mkdir -p src/includes
mkdir -p src/tools/linker
mkdir -p src/docs
